name: DummyPlayers
version: ${project.version}
description: ${project.description}
author: xTDKx
main: me.xTDKx.DP.PlayerSimulator
commands:
  dplayers:
    description: Spawn a fake player at a random location
    usage: /<command> [count] [radius]
    permission: playersimulator.spawn
  killbots:
    description: Disconnect all fake players
    permission: playersimulator.killbots
  debug:
    description: Show tick rate, memory usage, and number of chunks loaded
    permission: playersimulator.debug
permissions:
  playersimulator:
    description: Allow a player all plugin permissions
    children:
      playersimulator.spawnbot:
        description: Allow a player to spawn fake players
      playersimulator.killbots:
        description: Allow a player to kill off fake players
      playersimulator.debug:
        description: Allow a player to see debug info

